### ISSUE TITLE
Consider a property instead of a get-function

### ISSUE THREAD

**Issue by domenic** [WICG/keyboard-map#12]
Assuming #5 doesn't happen, I think the better design is `navigator.keyboard.map`, instead of `navigator.keyboard.getKeyboardMap()`. This is more natural for something that doesn't change often.

You'd want to upgrade the "may return the same object as long as the layout doesn't change" to a "must return the same object as long as the layout doesn't change".

**Comment by garykac** [comment]
API has been updated to return a Promise, so this is no longer applicable.
