### ISSUE TITLE
Are there grand plans for navigator.keyboard?

### ISSUE THREAD

**Issue by domenic** [WICG/keyboard-map#13]
Basically, is there a reason to indirect this behind `navigator.keyboard.getKeyboardMap()`, instead of `navigator.getKeyboardMap()`? For example, are you planning to put a lot more stuff into `navigator.keyboard` in the future?

**Comment by garykac** [comment]
We already have Keyboard Lock: https://w3c.github.io/keyboard-lock/

We initially had keyboard lock directly on navigator, but moved it onto the `keyboard` object once we realized that Keyboard Map might be coming along soon.

We *may* (I hope) be merging the specs together into a unified "keyboard" spec, but for the moment they are 2 separate documents.

So, plans, yes. But they don't feel terribly grand. ^_^

**Comment by domenic** [comment]
Got it, it was a bit confusing since this class defines the interface instead of using a partial. But I can understand how defining a partial would kind of imply picking one spec as "primary", and that might be better held off until you merge. For now, I'd suggest adding a cross-reference note explaining the situation a bit?
