### ISSUE TITLE
navigator.keyboard.getKeyboardMap() -> navigator.keyboard.getMap()?

### ISSUE THREAD

**Issue by domenic** [WICG/keyboard-map#15]
Seems less redundant.

**Comment by garykac** [comment]
or perhaps `getLayoutMap()`

**Comment by travisleithead** [comment]
Curious: the use cases usually call for just needing a few specific key map values--yet the API is designed to produce the entire keyboard map in one-shot--from an implementation standpoint, allocating all this memory and the time it takes to do so may not justify the use-cases, if (for example) the API kept the map internal, and exposed an API to just get a single key value returned for a specific code as input. For example:

```js
keyboard.getKey(code).then((key) => { …})
```
Probably this has been thought of already--would you mind writing down the design justification in the explainer document (and updating it's examples to match the new name `getLayoutMap`).

**Comment by garykac** [comment]
I've updated the explainer to discuss this briefly.

In summary, getting the entire (or most) of the layout mapping is a common use case for games. The WASD keys are used in the examples as a simplified stand-in for all the keys that a game might need.

When using Promises to get a set of keys (with this hypothetical `getKey` API), the code would look something like:

```
var keymap = {};
var k = navigator.keyboard.getKey;
Promise.all([k("KeyW"),k("KeyA"),k("KeyS"),k("KeyD"),
             k("KeyI"),k("KeyJ"),k("KeyK"),k("KeyL")]).then(values => {
               // Need to associate each return value with the code that produced it.
               // Index into |values| must match order of Promises.
               keymap["KeyW"] = values[0];
               keymap["KeyA"] = values[1];
               keymap["KeyS"] = values[2];
               keymap["KeyD"] = values[3];
               keymap["KeyI"] = values[4];
               keymap["KeyJ"] = values[5];
               keymap["KeyK"] = values[6];
               keymap["KeyL"] = values[7];
             }, () => {
               // Unable to get map
             })
```

which is..... ugly.

**Comment by travisleithead** [comment]
OK, thanks for the explanation. Appreciate the consideration.

**Comment by garykac** [comment]
Named: `getLayoutMap`
