### ISSUE TITLE
Duplicate definition of Keyboard interface

### ISSUE THREAD

**Issue by foolip** [WICG/keyboard-map#25]
In the [sum of all IDL](https://github.com/tidoust/reffy-reports/tree/master/whatwg/idl), there are two definitions of the Keyboard interface:
https://wicg.github.io/keyboard-lock/#keyboard-interface
https://wicg.github.io/keyboard-map/#keyboard-interface

This is a problem if trying to parse all IDL together to figure out the sum of all API surface, as I'm attempting now.

Making one of these a partial interface would fix the problem.

Twin issue: https://github.com/w3c/keyboard-lock/issues/51

**Comment by foolip** [comment]
@garykac can you take a look at this?

**Comment by garykac** [comment]
My first attempt at fixing it failed, but I'll take a look at it again. I should be a simple fix, but I don't remember  what blocked me last time.

I'll take a look at it again.

**Comment by foolip** [comment]
Ping @garykac

**Comment by garykac** [comment]
So, this seems like it **should** be a simple fix by just adding `partial` to one of the definitions, but `bikeshed` gives link errors in that case.

In this spec, we have the following in the [index.bs](https://github.com/WICG/keyboard-map/blob/main/index.bs) file:
```
<pre class="idl" data-highlight="webidl">
[SecureContext, Exposed=Window] interface Keyboard {
	Promise&lt;KeyboardLayoutMap> getLayoutMap();
};
</pre>

<div id="keyboard-idl" dfn-for="Keyboard">

	<div class="algorithm" data-algorithm="keyboard-getlayoutmap">
	<h4 id="h-keyboard-getlayoutmap"><dfn>getLayoutMap()</dfn></h4>

		...

	</div><!-- getLayoutMap() -->

</div><!-- dfn-for Keyboard -->
```

Changing it to a `partial interface Keyboard` results in the following bikeshed errors:

```
LINK ERROR: No 'idl-name' refs found for 'Keyboard;.
<a data-link-type="idl-name" data-lt="Keyboard">Keyboard</a>
LINK ERROR: No 'idl' refs found for 'Keyboard;.
{{Keyboard}}
LINK ERROR: No 'interface' refs found for 'Keyboard;.
<a data-lt="Keyboard" data-link-type="interface">Keyboard</a>
```

So it is not finding the interface definition in the KeyboardLock spec, even though the def is found in webref: https://github.com/w3c/webref/blob/master/ed/idl/keyboard-lock.idl

Clearly, I'm not linking this correctly, but I could not find a way to define this as a `partial interface` without link errors.  @tabatkins - any suggestions on how to fix this?

**Comment by tabatkins** [comment]
Ah, Bikeshed is not *yet* on webref; that project is stalled one step from the finish line at the moment, and I'll finish up this quarter. ^_^

keyboard-lock is indeed not in Shepherd, the current definition source. I've just added Keyboard Lock and Keyboard Map to Shepherd for now; give it a few minutes the `bikeshed update` to get the links to start working.

**Comment by garykac** [comment]
Thanks! That worked great.
