### ISSUE TITLE
Request comments from Moz

### ISSUE THREAD

**Issue by garykac** [WICG/keyboard-map#3]
@julienw

You wrote [Internationalize Your Keyboard Controls](https://hacks.mozilla.org/2017/03/internationalize-your-keyboard-controls/) last year and called out the need to be able to figure out "which letter is behind a specific key" in the "What's missing?" section.

Do you have any comments on the API described here?  Thanks!

**Comment by julienw** [comment]
Thanks for writing this proposal, I wasn't aware this was actually happening !

First, a quick disclaimer: I'm not a heavy user of the Keyboard API, I'm not a game developer. I'm a JavaScript developer that happens to use a keybord with the french AZERTY layout and got frustrated that so many online demos don't do this properly.

So I'll do my best but please keep this in mind :)

Some comments on the proposal.
* In the part [Describe Keyboard Shortcuts](https://github.com/WICG/keyboard-map/blob/master/proposal.md#describe-keyboard-shortcuts), while the general reasoning is right, the ship has sailed for some keys. For example `ctrl-Z` is what we usually use on french keyboards for undo too. I don't know what happen for other more different layouts (eg russian). So I believe that for this something more complicated will eventually need to happen, with a locale- or layout-specific way to define some currently used shortcuts.
  Of course I understand this is out of the scope for this proposal, but you may want to call this out in this paragraph.

* Now, about the proposal itself. I believe there are significant challenges, and maybe simply mapping from keys to codes isn't enough. Examples are:
  * some keys that aren't either dead keys or character keys: arrows, function keys, insertion/home/delete/backspace/End/Page down/Page up/etc.
  * the modifier keys themselves
  * the character keys that are more "logical": tab (forward/reverse), space
  * characters that are present in a few different positions: numbers and other keys in a numeric pad
  * about number keys: on french layouts they're in a "SHIFT" position while on most other layouts they're on the "normal" position. Yet I think we still want to mention these keys using their number on these keyboards.

  Instead, I believe we should map layout-independend keys (current `key` property) to layout-dependent keys (same values than the `key` property, but that have been mapped using the current keyboard layout).

Let's be more technical:
* I think `getKeyboardMap` should return a `Promise`. I don't know how difficult recovering all keys is and I think we shouldn't block the page's thread for this.

* we can have several keyboards plugged in on the same computer. So maybe we'd want `navigator.keyboard` as an array-like: `navigator.keyboard[0].getKeyboardMap()`. Index 0 is the primary keyboard (I don't know if this is a thing).

* similar idea: on mobile there are several keyboard types: characters, symbols, numeric, date... Maybe we could access them with `navigator.keyboard.numeric`? Not sure at all about this...

* I like the `keyboardchange` event. If I'd be nitpicky, I'd suggest `keyboardlayoutchange` ? The event would hold the index of the changed keyboard.

* what about keys that aren't on the current keyboard ? There are a lot of values for keys.

* about other proposals: I don't understand why Proposal C can't be standalone, why it's necessarily with Proposal A or B ? Maybe Proposal C could be more lightweight to the browser ?

* about the privacy issue's mitigation: some other possibilites:
  * is it possible to prevent this API from being used by 3rd-party scripts (scripts served from another domain that the main page -- subdomains are OK) ?
  * is it possible to "track" the data returned by this API, to make sure it can't be sent to any 3rd-party server ? I think no API does this at the moment...

Thanks for reading until here, always happy to provide more feedback in the future, or explain better some of the comments I made here. Basically the most important comment is about the mapping itself: I think we should map key values to key values.

**Comment by garykac** [comment]
Thanks for the comments and feedback. I've added links to some issues in the spec: https://wicg.github.io/keyboard-map/

>   * In the part Describe Keyboard Shortcuts, while the general reasoning is right, the ship has sailed for some keys. For example ctrl-Z is what we usually use on french keyboards for undo too. I don't know what happen for other more different layouts (eg russian). So I believe that for this something more complicated will eventually need to happen, with a locale- or layout-specific way to define some currently used shortcuts.
> Of course I understand this is out of the scope for this proposal, but you may want to call this out in this paragraph.

Good point. I'll point that out in the text.

>   * Now, about the proposal itself. I believe there are significant challenges, and maybe simply mapping from keys to codes isn't enough.

Note: we're mapping from `code` (the physical location) to `key` (the generated value)

> Examples are:
>      * some keys that aren't either dead keys or character keys: arrows, function keys, insertion/home/delete/backspace/End/Page down/Page up/etc.

We ignore them in this API because they are constant across locales and layouts. And any descriptive term that we returned would need to be translated ("Escape" -> "échap"). And for this translation, using the `code` value is sufficient (and the `key` value for most of those keys is basically identical to the `code`, cf. `Tab` vs. `Tab` and `ShiftLeft` vs. `Shift`).

>      * the modifier keys themselves
>      * the character keys that are more "logical": tab (forward/reverse), space
>      * characters that are present in a few different positions: numbers and other keys in a numeric pad

Same as above. We're only focusing on the [Writing System Keys](https://www.w3.org/TR/uievents-code/#writing-system-keys) because those are the ones that change between locales/layouts.

>      * about number keys: on french layouts they're in a "SHIFT" position while on most other layouts they're on the "normal" position. Yet I think we still want to mention these keys using their number on these keyboards.

Hmm... since the accented letters are the primary function of that key, I'm not sure we have a good way to do this.  I'll keep it in mind however. I wonder if there are similar situations for other layouts.

>   Instead, I believe we should map layout-independend keys (current key property) to layout-dependent keys (same values than the key property, but that have been mapped using the current keyboard layout).

The layout independent value is the `code` attribute, which is what we are using as a starting point. The `key` attribute is not layout independent, so I think that I'm misunderstanding you here.

> Let's be more technical:
>
> * I think getKeyboardMap should return a Promise. I don't know how difficult recovering all keys is and I think we shouldn't block the page's thread for this.

I've been considering whether or not that was necessary. I've opened a [tracking bug](https://github.com/WICG/keyboard-map/issues/5) for this.

> * we can have several keyboards plugged in on the same computer. So maybe we'd want navigator.keyboard as an array-like: navigator.keyboard[0].getKeyboardMap(). Index 0 is the primary keyboard (I don't know if this is a thing).

Revealing the number of physical keyboard connected could be used for fingerprinting, so unless there was a need (i.e., a use case) for this, I don't think it would be good to add it.

Also, even with multiple physical keyboards, they all share the same OS locale and layout so they should all produce the same value when the same (corresponding) key is pressed.

> * I like the keyboardchange event. If I'd be nitpicky, I'd suggest keyboardlayoutchange ? The event would hold the index of the changed keyboard.

I've opened a [tracking bug](https://github.com/WICG/keyboard-map/issues/6) for the name suggestion.  We have a naming review process that should consider the options.

> * what about keys that aren't on the current keyboard ? There are a lot of values for keys.

That's why the returned dictionary used `code` values, and only for the [writing system keys](https://www.w3.org/TR/uievents-code/#writing-system-keys). There are only 51 keys that we need to worry about (since they're the only ones that are not consistent across layouts).

> * about other proposals: I don't understand why Proposal C can't be standalone, why it's necessarily with Proposal A or B ? Maybe Proposal C could be more lightweight to the browser ?

Proposal C needs both the `code` and the layout, which means that there needs to be some web-standard way to specify the layout.

Our initial version of this API was similar to C, but without the layout parameter. But all the use cases that we're aware of want basically the entire keyboard map, so it's easier to just return the map instead of requiring that user request each mapping individually.

> * about the privacy issue's mitigation: some other possibilites:
>
>    * is it possible to prevent this API from being used by 3rd-party scripts (scripts served from another domain that the main page -- subdomains are OK) ?

Yes, that's possible, but there's a surprising amount of useful content that runs in &lt;iframe&gt;s so I wouldn't want to impose this unless it's necessary.

>    * is it possible to "track" the data returned by this API, to make sure it can't be sent to any 3rd-party server ? I think no API does this at the moment...

Once the data is returned to the JS code on the page, there is no way to track or prevent it from being used however the page wants.

> Thanks for reading until here, always happy to provide more feedback in the future, or explain better some of the comments I made here. Basically the most important comment is about the mapping itself: I think we should map key values to key values.

Thanks for taking the time to comment on the document!

**Comment by julienw** [comment]
Thanks for your detailed answers! They make sense to me and I don't have much more to add.

I just want to answer to this:
>>  Instead, I believe we should map layout-independend keys (current key property) to layout-dependent keys (same values than the key property, but that have been mapped using the current keyboard layout).

> The layout independent value is the code attribute, which is what we are using as a starting point. The key attribute is not layout independent, so I think that I'm misunderstanding you here.

Yeah, I totally exchanged `key` and `code` in my comment. I think that's because to me the word "key" is the physical key, this feels backwards then that `key` maps to the layout-dependent code. But that's how it is :)

Anyway, here is what I wanted to say, with the right words.

I believe we should map layout-independent `code`s (current `code` property) to layout-dependent `code`s (same values than the `code` property, but that have been mapped using the current keyboard layout).

Basically, we could have a mapping object that, for AZERTY layouts, would map 'KeyA' to 'KeyQ' (this means: with the current layout, the key that corresponds to `KeyA` on the reference keyboard triggers the action for the key that corresponds to `KeyQ` on the reference keyboard), while 'Digit1' would map to 'Digit1' (the key hasn't moved). Simarly `Semicolon` would map to `KeyM`, while `KeyM` woud map to `Comma`. Because what's important to know is which physical keys are moved to which location on the keyboard.

But now that I look at it more closely, I see it's not possible to do it for all keys. For example the code `BracketRight` holds `$£ø` on my azerty keyboard, and the code `Quote` holds `ù%`. There's no `code` values for those. This means we'd need to create new `code` values for all keyboard layouts, and this doesn't scale.

All this to say I now think the API is the right API. Thanks for your patience!

**Comment by garykac** [comment]
Thanks for your comments!
