### ISSUE TITLE
Name of "keyboardchange" event

### ISSUE THREAD

**Issue by garykac** [WICG/keyboard-map#6]
Should it be:
* keyboardchange (current)
* keyboardlayoutchange

or something else?

**Comment by masayuki-nakano** [comment]
**I** like keyboardlayoutchange better since "keyboard changed" sounds like that physical thing occurred.

And I understand the event is NOT fired when IME's input mode is changed. On macOS, each input mode of IME is treated as a keyboard layout. So, browsers must need some additional check on macOS.

@smaug---- any ideas?

**Comment by masayuki-nakano** [comment]
Or, should browsers treat changing input mode of IME as keyboard layout change in all platforms?? I'm not familiar with Android, I don't know it's possible on Android, though.

**Comment by smaug----** [comment]
Yeah, keyboardlayoutchange sounds better.
Is that just a notification or will it reveal the actual layout? Since if latter, it can be possibly a privacy issue, which Tor at least would probably like to avoid.

**Comment by masayuki-nakano** [comment]
@smaug---- Probably, Tor will mimic most famous keyboard layout for the users of the web apps anyway (like KeyboardEvent.shitKey, KeyboardEvent.code etc). So, we must not need to worry about Tor here.

**Comment by garykac** [comment]
@smaug---- it's just a notification - it doesn't reveal anything about the layout.
We expect people to follow up with getKeyboardMap() to get info about the layout.

**Comment by domenic** [comment]
keyboardmapchange? Since that ties it to the API you would use this in conjunction with?

**Comment by garykac** [comment]
I'm leaning toward `keyboardlayoutchange` for 2 reasons:
* An event that fires for layout changes may be useful for other things in the future.
* We'll be firing the event when the layout changes, which may not necessarily change the map (e.g., if the highest ASCII keyboard doesn't change).
* I think most web devs are more familiar immediately with "keyboard layout" whereas they might wonder what exactly a "keyboard map" is

**Comment by garykac** [comment]
(make that 3 reasons ^_^)

**Comment by garykac** [comment]
See discussion of the event name in #17

**Comment by garykac** [comment]
Name changed to "layoutchange" in https://github.com/WICG/keyboard-map/commit/843570d2e7851ed9f794601fd9fc5c0a42f334d4
