### ISSUE TITLE
"keyboardchange" event trigger conditions could be more specific

### ISSUE THREAD

**Issue by cynthia** [WICG/keyboard-map#7]
Brought up during TAG review: https://github.com/w3ctag/design-reviews/issues/238 and #4 

The "keyboardchange" event section is not entirely clear on what an implementor should do - it would be helpful for implementor consistency to have this section made a bit more specific.

It doesn't necessarily have to be normative, but having hints on which exact cases would help making implementations (even within the same platform) be a bit more consistent.

Multiple keyboard cases are related to this - laptop on desk with external keyboard scenario examples come to mind, in this case when should the event fire?

(I personally would go as far as noticing OS specific events/APIs as non-normative notes)

**Comment by travisleithead** [comment]
Also, the explainer notes that this event fires on the `document`. The actual spec doesn't say where the event fires at all, nor what `Event` (or derived) type it should be (e.g., does the event carry the old and new keyboard layout? I assume not...)

**Comment by garykac** [comment]
I've updated the `keyboardlayoutchange` section. Please let me know if there is anything else you think should be added. Thanks!

**Comment by cynthia** [comment]
Changes look good. Thanks!
